<a href="https://colab.research.google.com/github/prathamshah-09/AI-Engineer-365-Careers/blob/main/Text_processing_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#upload trip advisor hotel reviews csv

In [2]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords
import re

In [4]:
df = pd.read_csv('tripadvisor_hotel_reviews.csv')
df.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [10]:
#lowercase
df['review_lowercase'] = df['Review'].str.lower()
df.head()

                                              Review  ...                                   review_lowercase
0  nice hotel expensive parking got good deal sta...  ...  nice hotel expensive parking got good deal sta...
1  ok nothing special charge diamond member hilto...  ...  ok nothing special charge diamond member hilto...
2  nice rooms not 4* experience hotel monaco seat...  ...  nice rooms not 4* experience hotel monaco seat...
3  unique, great stay, wonderful time hotel monac...  ...  unique, great stay, wonderful time hotel monac...
4  great stay great stay, went seahawk game aweso...  ...  great stay great stay, went seahawk game aweso...

[5 rows x 3 columns]

In [13]:
#stopwords removal
nltk.download('stopwords')
en_stopwords = stopwords.words('english')
en_stopwords.remove('not')
df['review_no_stopwords'] = df['review_lowercase'].apply(lambda x: ' '.join([word for word in x.split() if word not in (en_stopwords)]))
df.head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

                                              Review  ...                                review_no_stopwords
0  nice hotel expensive parking got good deal sta...  ...  nice hotel expensive parking got good deal sta...
1  ok nothing special charge diamond member hilto...  ...  ok nothing special charge diamond member hilto...
2  nice rooms not 4* experience hotel monaco seat...  ...  nice rooms not 4* experience hotel monaco seat...
3  unique, great stay, wonderful time hotel monac...  ...  unique, great stay, wonderful time hotel monac...
4  great stay great stay, went seahawk game aweso...  ...  great stay great stay, went seahawk game aweso...

[5 rows x 4 columns]

In [14]:
#Punctuation
df['review_no_stopwords_no_punct'] = df \
                                    .apply(lambda x: \
                                    re.sub(r"[*]", \
                                    "star", \
                                    x['review_no_stopwords'] \
                                    ), axis=1)
df.head()

                                              Review  ...                       review_no_stopwords_no_punct
0  nice hotel expensive parking got good deal sta...  ...  nice hotel expensive parking got good deal sta...
1  ok nothing special charge diamond member hilto...  ...  ok nothing special charge diamond member hilto...
2  nice rooms not 4* experience hotel monaco seat...  ...  nice rooms not 4star experience hotel monaco s...
3  unique, great stay, wonderful time hotel monac...  ...  unique, great stay, wonderful time hotel monac...
4  great stay great stay, went seahawk game aweso...  ...  great stay great stay, went seahawk game aweso...

[5 rows x 5 columns]

In [16]:
#Tokenizing
nltk.download('punkt_tab')
df['tokenized']=df.apply(lambda row: nltk.word_tokenize(row['review_no_stopwords_no_punct']), axis=1)
df.head()

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

                                              Review  ...                                          tokenized
0  nice hotel expensive parking got good deal sta...  ...  [nice, hotel, expensive, parking, got, good, d...
1  ok nothing special charge diamond member hilto...  ...  [ok, nothing, special, charge, diamond, member...
2  nice rooms not 4* experience hotel monaco seat...  ...  [nice, rooms, not, 4star, experience, hotel, m...
3  unique, great stay, wonderful time hotel monac...  ...  [unique, ,, great, stay, ,, wonderful, time, h...
4  great stay great stay, went seahawk game aweso...  ...  [great, stay, great, stay, ,, went, seahawk, g...

[5 rows x 6 columns]

In [17]:
#Stemming
ps = PorterStemmer()
df['stemmed'] = df['tokenized'].apply(lambda x: [ps.stem(y) for y in x])
df.head()

                                              Review  ...                                            stemmed
0  nice hotel expensive parking got good deal sta...  ...  [nice, hotel, expens, park, got, good, deal, s...
1  ok nothing special charge diamond member hilto...  ...  [ok, noth, special, charg, diamond, member, hi...
2  nice rooms not 4* experience hotel monaco seat...  ...  [nice, room, not, 4star, experi, hotel, monaco...
3  unique, great stay, wonderful time hotel monac...  ...  [uniqu, ,, great, stay, ,, wonder, time, hotel...
4  great stay great stay, went seahawk game aweso...  ...  [great, stay, great, stay, ,, went, seahawk, g...

[5 rows x 7 columns]

In [18]:
#Lemmatization
lemmatizer = WordNetLemmatizer()
nltk.download('wordnet')
df['lemmatized'] = df['tokenized'].apply(lambda x: [lemmatizer.lemmatize(y) for y in x])
df.head()

[nltk_data] Downloading package wordnet to /root/nltk_data...

                                              Review  ...                                         lemmatized
0  nice hotel expensive parking got good deal sta...  ...  [nice, hotel, expensive, parking, got, good, d...
1  ok nothing special charge diamond member hilto...  ...  [ok, nothing, special, charge, diamond, member...
2  nice rooms not 4* experience hotel monaco seat...  ...  [nice, room, not, 4star, experience, hotel, mo...
3  unique, great stay, wonderful time hotel monac...  ...  [unique, ,, great, stay, ,, wonderful, time, h...
4  great stay great stay, went seahawk game aweso...  ...  [great, stay, great, stay, ,, went, seahawk, g...

[5 rows x 8 columns]

In [20]:
#N-grams
tokens_clean = sum(df['lemmatized'],[])

In [21]:
#unigrams
unigrams = (pd.Series(nltk.ngrams(tokens_clean,1)).value_counts())
unigrams.head(10)

(,,)           1094
(hotel,)        292
(room,)         275
(great,)        126
(not,)          122
(stay,)          95
(staff,)         90
(n't,)           81
(seattle,)       79
(location,)      78
Name: count, dtype: int64

In [22]:
#bigrams
bigrams = (pd.Series(nltk.ngrams(tokens_clean,2)).value_counts())
bigrams.head(10)

(,, room)            55
(hotel, ,)           41
(,, great)           41
(room, ,)            37
(,, hotel)           31
(stay, ,)            26
(,, staff)           26
(great, location)    24
(space, needle)      21
(,, nice)            20
Name: count, dtype: int64

In [23]:
ngrams_4 = (pd.Series(nltk.ngrams(tokens_clean,4)).value_counts())
ngrams_4.head(10)

(pike, place, market, ,)                4
(staff, friendly, helpful, ,)           3
(room, really, comfortable, clean)      2
(nice, view, space, needle)             2
(,, staff, friendly, helpful)           2
(,, definitely, stay, ,)                2
(,, overall, nice, experience)          2
(center, ,, great, location)            2
(needle, experience, music, project)    2
(market, seattle, art, museum)          2
Name: count, dtype: int64